fix(bug): fix discord link
freeCodeCamp/contribute pull request #228
Opened 2024-07-18 17:45 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #217

2024-07-19 01:06 UTC, michaelhiiva commented
@gagan-bhullar-tech The link still does not work for me. I think you are looking for https://discord.com/invite/freecodecamp which is on https://discord.com/servers/freecodecamp-org-official-fi-fo-692816967895220344.

2024-07-19 01:11 UTC, gagan-bhullar-tech commented
@michaelhiiva the link is updated.

2024-08-07 16:13 UTC, Blindspot22 commented
> @michaelhiiva thanks. Link is updated.

@gagan-bhullar-tech Seems like this your PR has not still yet been approved for merging.
Maybe you should try tagging the reviewer in the comment section again for it to be reviewed.

2024-08-07 16:30 UTC, raisedadead requested changes

2024-08-07 16:30 UTC, raisedadead commented on astro.config.mjs
> +        discord: 'https://discord.com/invite/freecodecamp'
```suggestion
        discord: 'https://chat.freecodecamp.org'
```

2024-08-07 16:32 UTC, raisedadead commented
Thanks for the PR - I have updated it after discussing it with the team. We are going to use a more permanent public link instead.

2024-08-07 16:32 UTC, raisedadead approved these changes

2024-08-07 16:33 UTC, merged